# Site settings
title: Rico's Nerd Cluster
title: Rico's Nerd Cluster
SEOTitle: Rico贾若童的博客 | Rico's Blog
header-img: img/home-bg.jpg
email: ruotongjia2020@u.northwestern.com
description: "这里是 @Rico贾若童 的个人博客，与你一起发现更大的世界 | To reach a port we must sail, sometimes with the wind, and sometimes against it."
keyword: "Robot Navigation, SLAM, C++, Python, Deep Learning"
url: "https://ricojia.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#facebook_username:  huxpro
linkedin_username:  RicoJia
github_username: RicoJia

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "" # Format: UA-xxxxxx-xx

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个有 swag 的机器人工程师 <br> Robotics @ Northwestern University"
sidebar-avatar: https://github.com/user-attachments/assets/645a8857-46ad-47ef-b214-e703f04f7ce3 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Sebastian Castro", href: "https://roboticseabass.com/" },
  ]
